### ISSUE TITLE
"mkenv.sh --test" failing on clean install 

### ISSUE THREAD

**Issue by BillRainford** [FNNDSC/ChRIS-E2E#16]
[redacted]$ oc status
In project My Project (myproject) on server https://localhost:8443

http://pfioh-myproject.127.0.0.1.nip.io to pod port 5055-tcp (svc/pfioh)
  dc/pfioh deploys docker.io/fnndsc/pfioh:latest 
    deployment #1 deployed about a minute ago - 1 pod

http://pman-myproject.127.0.0.1.nip.io to pod port 5010-tcp (svc/pman)
  dc/pman deploys docker.io/fnndsc/pman:latest 
    deployment #2 deployed about a minute ago - 1 pod
    deployment #1 failed about a minute ago: newer deployment was found running

4 infos identified, use 'oc status -v' to see details.
[redacted]$ ChRIS-E2E/mkenv.sh --test
*** Testing if openshift pman can be reached with hello
{
    "status": true,
    "RESTheader": "POST /api/v1/cmd/api/v1/cmd HTTP/1.1\r",
    "RESTverb": "POST",
    "action": "hello",
    "path": "/api/v1/cmd/api/v1/cmd",
    "receivedByServer": [
        "POST /api/v1/cmd/api/v1/cmd HTTP/1.1\r",
        "User-Agent: PycURL/7.43.0.2 libcurl/7.59.0 OpenSSL/1.1.0i zlib/1.2.11 libidn2/2.0.5 libpsl/0.20.2 (+libidn2/2.0.4) libssh/0.8.6/openssl/zlib nghttp2/1.32.1\r",
        "Accept: */*\r",
        "Authorization: bearer password\r",
        "Content-Length: 90\r",
        "Content-Type: application/x-www-form-urlencoded\r",
        "Host: pman-myproject.127.0.0.1.nip.io\r",
        "X-Forwarded-Host: pman-myproject.127.0.0.1.nip.io\r",
        "X-Forwarded-Port: 80\r",
        "X-Forwarded-Proto: http\r",
        "Forwarded: for=127.0.0.1;host=pman-myproject.127.0.0.1.nip.io;proto=http\r",
        "X-Forwarded-For: 127.0.0.1\r",
        "\r",
        "{\"payload\": {\"action\": \"hello\", \"meta\": {\"askAbout\": \"sysinfo\", \"echoBack\": \"Hi there!\"}}}"
    ],
    "client_json_payload": "{\"payload\": {\"action\": \"hello\", \"meta\": {\"askAbout\": \"sysinfo\", \"echoBack\": \"Hi there!\"}}}",
    "client_json_len": 90,
    "payloadsize": 90,
    "meta": {
        "askAbout": "sysinfo",
        "echoBack": "Hi there!"
    },
    "d_ret": {
        "name": "pman",
        "version": "2.0.0.6",
        "sysinfo": {
            "system": "Linux",
            "machine": "x86_64",
            "platform": "Linux-4.17.12-200.fc28.x86_64-x86_64-with-Ubuntu-18.04-bionic",
            "uname": [
                "Linux",
                "pman-2-kfv9j",
                "4.17.12-200.fc28.x86_64",
                "#1 SMP Fri Aug 3 15:01:13 UTC 2018",
                "x86_64",
                "x86_64"
            ],
            "version": "#1 SMP Fri Aug 3 15:01:13 UTC 2018",
            "memory": [
                8357773312,
                3272900608,
                60.8,
                4692557824,
                150319104,
                3590135808,
                3754758144,
                380112896,
                3134783488,
                79060992,
                678612992
            ],
            "cpucount": 2,
            "loadavg": [
                2.77,
                3.45,
                1.87
            ],
            "cpu_percent": 50.2,
            "hostname": "pman-2-kfv9j",
            "inet": "172.17.0.7"
        }
    }
}
*** Testing if openshift pfioh can be reached with hello
"200 OK\r\nContent-Type: text/html; charset=UTF-8\r\nContent-Length: 791\r\n\r\n{\"stdout\": {\"d_ret\": {\"name\": \"pfioh\", \"version\": \"1.6.0.2\", \"sysinfo\": {\"system\": \"Linux\", \"machine\": \"x86_64\", \"platform\": \"Linux-4.17.12-200.fc28.x86_64-x86_64-with-Ubuntu-18.04-bionic\", \"uname\": [\"Linux\", \"pfioh-1-bq5rj\", \"4.17.12-200.fc28.x86_64\", \"#1 SMP Fri Aug 3 15:01:13 UTC 2018\", \"x86_64\", \"x86_64\"], \"version\": \"#1 SMP Fri Aug 3 15:01:13 UTC 2018\", \"memory\": [8357773312, 3272486912, 60.8, 4692979712, 149536768, 3593842688, 3752058880, 380112896, 3135143936, 79060992, 679116800], \"cpucount\": 2, \"loadavg\": [2.77, 3.45, 1.87], \"cpu_percent\": 55.0, \"hostname\": \"pfioh-1-bq5rj\", \"inet\": \"172.17.0.3\"}, \"User-agent\": \"PycURL/7.43.0.2 libcurl/7.59.0 OpenSSL/1.1.0i zlib/1.2.11 libidn2/2.0.5 libpsl/0.20.2 (+libidn2/2.0.4) libssh/0.8.6/openssl/zlib nghttp2/1.32.1\"}, \"status\": true}}"
*** Testing if openshift pfioh can be reached with hello
"200 OK\r\nContent-Type: text/html; charset=UTF-8\r\nContent-Length: 791\r\n\r\n{\"stdout\": {\"d_ret\": {\"name\": \"pfioh\", \"version\": \"1.6.0.2\", \"sysinfo\": {\"system\": \"Linux\", \"machine\": \"x86_64\", \"platform\": \"Linux-4.17.12-200.fc28.x86_64-x86_64-with-Ubuntu-18.04-bionic\", \"uname\": [\"Linux\", \"pfioh-1-bq5rj\", \"4.17.12-200.fc28.x86_64\", \"#1 SMP Fri Aug 3 15:01:13 UTC 2018\", \"x86_64\", \"x86_64\"], \"version\": \"#1 SMP Fri Aug 3 15:01:13 UTC 2018\", \"memory\": [8357773312, 3271954432, 60.9, 4693336064, 148983808, 3594100736, 3751723008, 380125184, 3135328256, 79060992, 679247872], \"cpucount\": 2, \"loadavg\": [2.77, 3.45, 1.87], \"cpu_percent\": 66.3, \"hostname\": \"pfioh-1-bq5rj\", \"inet\": \"172.17.0.3\"}, \"User-agent\": \"PycURL/7.43.0.2 libcurl/7.59.0 OpenSSL/1.1.0i zlib/1.2.11 libidn2/2.0.5 libpsl/0.20.2 (+libidn2/2.0.4) libssh/0.8.6/openssl/zlib nghttp2/1.32.1\"}, \"status\": true}}"
*** Testing if remote pman and pfioh can be reached with hello

"(52, 'Empty reply from server')"
*** Testing if the backend can be reached by user chris
Traceback (most recent call last):
  File "/usr/local/bin/pfurl", line 383, in <module>
    print(json.dumps(json.loads(pfurl()), indent=int(args.jsonpprintindent)))
  File "/usr/local/lib/python3.6/site-packages/pfurl/pfurl.py", line 1344, in __call__
    d_ret = self.pull_core()
  File "/usr/local/lib/python3.6/site-packages/pfurl/pfurl.py", line 565, in pull_core
    c.perform()
pycurl.error: (56, 'Recv failure: Connection reset by peer')
*** Testing if the backend can be reached by user cube
Traceback (most recent call last):
  File "/usr/local/bin/pfurl", line 383, in <module>
    print(json.dumps(json.loads(pfurl()), indent=int(args.jsonpprintindent)))
  File "/usr/local/lib/python3.6/site-packages/pfurl/pfurl.py", line 1344, in __call__
    d_ret = self.pull_core()
  File "/usr/local/lib/python3.6/site-packages/pfurl/pfurl.py", line 565, in pull_core
    c.perform()
pycurl.error: (56, 'Recv failure: Connection reset by peer')
*** Running integration tests
~/Documents/RedHat/ChRIS_ultron_backEnd ~/Documents/RedHat
Creating test database for alias 'default'...
System check identified no issues (0 silenced).
...................................................................................................................F......................F...............................................................................................................
======================================================================
FAIL: test_integration_mananger_can_check_plugin_app_exec_status (plugininstances.tests.test_manager.PluginAppManagerTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/src/chris_backend/plugininstances/tests/test_manager.py", line 205, in test_integration_mananger_can_check_plugin_app_exec_status
    self.assertEqual(pl_inst.status, 'finishedSuccessfully')
AssertionError: 'started' != 'finishedSuccessfully'
- started
+ finishedSuccessfully

======================================================================
FAIL: test_integration_plugin_instance_detail_success (plugininstances.tests.test_views.PluginInstanceDetailViewTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/src/chris_backend/plugininstances/tests/test_views.py", line 254, in test_integration_plugin_instance_detail_success
    self.assertContains(response, "finishedSuccessfully")
  File "/usr/local/lib/python3.6/dist-packages/django/test/testcases.py", line 369, in assertContains
    self.assertTrue(real_count != 0, msg_prefix + "Couldn't find %s in response" % text_repr)
AssertionError: False is not true : Couldn't find 'finishedSuccessfully' in response

----------------------------------------------------------------------
Ran 250 tests in 176.624s

FAILED (failures=2)
Destroying test database for alias 'default'...
~/Documents/RedHat
[redacted]$

**Comment by BillRainford** [comment]
I was working through the new hire guide readme (https://github.com/FNNDSC/ChRIS-E2E/blob/master/README.md) and setting things up. I made it through all the steps and see the '--test' option results in two test failures which if legit should be fixed.
